version: "3"
services:
  postgres:
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_DB: meli
      POSTGRES_USER: meli-user
      POSTGRES_PASSWORD: meli-pass
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-meli:/var/lib/postgresql/data
    ports:
      - "25432:5432"
    networks:
      - meli-network
  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - meli-network
  ip-meli:
    build:
      context: .
    image: 'ip-meli:1.0.0'
    environment:
      DATASOURCE_URL: jdbc:postgresql://postgres:5432/meli
      CACHE_HOST: redis
      API_THIRD_TIMEOUT: "5"
      API_IP_TO_COUNTRY_URL: https://api.ip2country.info/ip?
      API_REST_COUNTRIES_URL: https://restcountries.eu/rest/v2/alpha/
      API_FIXER_URL: http://data.fixer.io/api/latest
      API_FIXER_KEY: 780559c9b0110a2ea1ab42491a4f9b1b
    ports:
      - '8080:8080'
    networks:
      - meli-network
    depends_on:
      - postgres
      - redis
volumes:
  db-meli:
networks:
  meli-network:
    driver: bridge

