spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "${DATASOURCE_URL:jdbc:postgresql://localhost:25432/meli}"
    username: meli-user
    password: meli-pass
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
  jpa:
    show-sql: false
    open-in-view: false
  redis:
    host: "${CACHE_HOST:localhost}"
    port: 6379

challenge:
  third:
    api:
      ip2country:
        url: "${API_IP_TO_COUNTRY_URL:https://api.ip2country.info/ip?}"
      restcountries:
        url: "${API_REST_COUNTRIES_URL:https://restcountries.eu/rest/v2/alpha/}"
      fixer:
        url: "${API_FIXER_URL:http://data.fixer.io/api/latest}"
        key: "${API_FIXER_KEY:780559c9b0110a2ea1ab42491a4f9b1b}"
